import pytest
from moto import mock_aws
from python.api_subscriptions.get_account_salary_transactions import get_account_salary_transactions


@pytest.mark.parametrize(
    "event, expected_result",
    [
        # Account with salary transactions
        (
            {"entity_id": "4e1bf704-8dad-42f1-8be1-af99cd19afe5", "account_id": "1145da38-a41b-4d8e-8bac-249ea471c4ed", "to_reject_account": False},
            [
                {
                    "transaction_type": "credit",
                    "transaction_note": "ACH/SAL-AMAZONDEVELCENTI/Sal  Adv Dec 104861382",
                    "chq_num": "",
                    "amount": 76900.0,
                    "balance": 76900.0,
                    "date": "2022-12-01 00:00:00",
                    "hash": "0a6d4699d6bd8bb8f1b5a78206f1193d",
                    "category": "",
                    "employer_name": None,
                    "salary_month": "Nov-2022",
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "ACH/SAL-AMAZONDEVELCENTI/Sal  Adv Feb 104861382 0",
                    "chq_num": "",
                    "amount": 77200.0,
                    "balance": 77200.0,
                    "date": "2023-02-02 00:00:00",
                    "hash": "380169fd4fd393109dec4722a72c05bc",
                    "category": "",
                    "employer_name": None,
                    "salary_month": "Jan-2023",
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "ACH/SAL-AMAZONDEVELCENTI/Sal  Adv Mar 104861382 0",
                    "chq_num": "",
                    "amount": 64487.0,
                    "balance": 64487.0,
                    "date": "2023-03-02 00:00:00",
                    "hash": "fd3a8bae42a83885fb7b90e8182a6554",
                    "category": "",
                    "employer_name": None,
                    "salary_month": "Feb-2023",
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "ACH/SAL-AMAZONDEVELCENTI/Sal  Adv May 104861382 0",
                    "chq_num": "",
                    "amount": 85000.0,
                    "balance": 85000.0,
                    "date": "2023-05-03 00:00:00",
                    "hash": "c4d8f77434e7e87d8f2675573aae4919",
                    "category": "",
                    "employer_name": None,
                    "salary_month": "Apr-2023",
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "3 ACH/SAL-AMAZONDEVELCENTI/SAL",
                    "chq_num": " -",
                    "amount": 81900.0,
                    "balance": 81900.0,
                    "date": "2024-02-02 00:00:00",
                    "hash": "41f3a69bb28d330f9ad2beb91ac36c4e",
                    "category": "Salary",
                    "employer_name": None,
                    "salary_month": "Jan-2024",
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "2 ACH/SAL-AMAZONDEVELCENTI/MAR SAL 2024 104861382 0",
                    "chq_num": " -  ",
                    "amount": 57888.0,
                    "balance": 57888.0,
                    "date": "2024-03-28 00:00:00",
                    "hash": "155903f40110e28b8fa1545a28a94467",
                    "category": "Salary",
                    "employer_name": None,
                    "salary_month": "Feb-2024",
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "76C3A941 ACH/SAL-AMAZONDEVELCENTI/SAL",
                    "chq_num": " -",
                    "amount": 79017.0,
                    "balance": 79017.0,
                    "date": "2024-04-02 00:00:00",
                    "hash": "c5c516ba386b2c1b87570586190edaa9",
                    "category": "Salary",
                    "employer_name": None,
                    "salary_month": "Mar-2024",
                },
            ],
        ),
        (
            {
                "entity_id": "4e1bf704-8dad-42f1-8be1-af99cd19afe5",
                "account_id": "1145da38-a41b-4d8e-8bac-249ea471c4ed",
                "to_reject_account": False,
                "enable_metadata": True,
            },
            [
                {
                    "transaction_type": "credit",
                    "transaction_note": "ACH/SAL-AMAZONDEVELCENTI/Sal  Adv Dec 104861382",
                    "chq_num": "",
                    "amount": 76900.0,
                    "balance": 76900.0,
                    "date": "2022-12-01 00:00:00",
                    "hash": "0a6d4699d6bd8bb8f1b5a78206f1193d",
                    "category": "",
                    "employer_name": None,
                    "salary_month": "Nov-2022",
                    "metadata": {
                        "unclean_merchant": "",
                        "transaction_channel": "salary",
                        "description": "",
                    },
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "ACH/SAL-AMAZONDEVELCENTI/Sal  Adv Feb 104861382 0",
                    "chq_num": "",
                    "amount": 77200.0,
                    "balance": 77200.0,
                    "date": "2023-02-02 00:00:00",
                    "hash": "380169fd4fd393109dec4722a72c05bc",
                    "category": "",
                    "employer_name": None,
                    "salary_month": "Jan-2023",
                    "metadata": {
                        "unclean_merchant": "",
                        "transaction_channel": "salary",
                        "description": "",
                    },
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "ACH/SAL-AMAZONDEVELCENTI/Sal  Adv Mar 104861382 0",
                    "chq_num": "",
                    "amount": 64487.0,
                    "balance": 64487.0,
                    "date": "2023-03-02 00:00:00",
                    "hash": "fd3a8bae42a83885fb7b90e8182a6554",
                    "category": "",
                    "employer_name": None,
                    "salary_month": "Feb-2023",
                    "metadata": {
                        "unclean_merchant": "",
                        "transaction_channel": "salary",
                        "description": "",
                    },
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "ACH/SAL-AMAZONDEVELCENTI/Sal  Adv May 104861382 0",
                    "chq_num": "",
                    "amount": 85000.0,
                    "balance": 85000.0,
                    "date": "2023-05-03 00:00:00",
                    "hash": "c4d8f77434e7e87d8f2675573aae4919",
                    "category": "",
                    "employer_name": None,
                    "salary_month": "Apr-2023",
                    "metadata": {
                        "unclean_merchant": "",
                        "transaction_channel": "salary",
                        "description": "",
                    },
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "3 ACH/SAL-AMAZONDEVELCENTI/SAL",
                    "chq_num": " -",
                    "amount": 81900.0,
                    "balance": 81900.0,
                    "date": "2024-02-02 00:00:00",
                    "hash": "41f3a69bb28d330f9ad2beb91ac36c4e",
                    "category": "Salary",
                    "employer_name": None,
                    "salary_month": "Jan-2024",
                    "metadata": {
                        "unclean_merchant": "",
                        "transaction_channel": "salary",
                        "description": "",
                    },
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "2 ACH/SAL-AMAZONDEVELCENTI/MAR SAL 2024 104861382 0",
                    "chq_num": " -  ",
                    "amount": 57888.0,
                    "balance": 57888.0,
                    "date": "2024-03-28 00:00:00",
                    "hash": "155903f40110e28b8fa1545a28a94467",
                    "category": "Salary",
                    "employer_name": None,
                    "salary_month": "Feb-2024",
                    "metadata": {
                        "unclean_merchant": "",
                        "transaction_channel": "salary",
                        "description": "",
                    },
                },
                {
                    "transaction_type": "credit",
                    "transaction_note": "76C3A941 ACH/SAL-AMAZONDEVELCENTI/SAL",
                    "chq_num": " -",
                    "amount": 79017.0,
                    "balance": 79017.0,
                    "date": "2024-04-02 00:00:00",
                    "hash": "c5c516ba386b2c1b87570586190edaa9",
                    "category": "Salary",
                    "employer_name": None,
                    "salary_month": "Mar-2024",
                    "metadata": {
                        "unclean_merchant": "",
                        "transaction_channel": "salary",
                        "description": "",
                    },
                },
            ],
        ),
        # Account with no salary transactions
        ({"entity_id": "672dd54b-d556-4315-8e12-0aa5337f147e", "account_id": "4cd9ebf5-be03-4172-941f-91b01aa3dfc0", "to_reject_account": False}, []),
    ],
)
@mock_aws
def test_get_account_salary_transactions(event, expected_result, mocker, aws_dynamodb):
    assert get_account_salary_transactions(event) == expected_result
