ACTION_NOT_TAKEN = 0
ACTION_TO_BE_REVIEWED = 1
ACTION_DONE = 2

CLOSE_ALL_WORKER_THREADS = False

DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
DEFAULT_AWS_REGION = 'ap-south-1'
IDENTITY_NULL_TEMPLATE_REDIS_KEY = '{}_{}_{}'
REDIS_KEY_INVALID_TEXT_BBOX_VANILLA = '{}_invalid_text_bbox'

BULK_PDF_DOWNLOAD_KEY = 'bulk_pdf_download'
UPDATE_STATE_RETRIGGER_REPEAT_AFTER = 600

QUALITY_DATABASE_NAME = "quality_db"
PORTAL_DATABASE_NAME = "portal_db"