name: Run Unit Test via Pytest

on: 
  pull_request:

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
            submodules: recursive
            token: ${{ secrets.GH_API_TOKEN }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.docker.txt ]; then pip install -r requirements.docker.txt; fi
          if [ -f local_wheels/category-0.0.1-py2.py3-none-any.whl ]; then pip install local_wheels/category-0.0.1-py2.py3-none-any.whl; fi
          pip install pytest
          pip install pytest-mock
          pip install pytest-cov
          pip install moto
      - name: Test with pytest
        run: |
          coverage run --source=tests -m pytest -v --disable-warnings -W ignore::DeprecationWarning tests/
      - name: Generate Coverage Report
        run: |
          coverage xml
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage.xml
          title: Coverage Report
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          unique-id-for-comment: python3.10