from enum import Enum


class FraudTypeEnum(Enum):
    AUTHOR_FRAUD = "author_fraud"
    DATE_FRAUD = "date_fraud"
    FONT_AND_ENCRYPTION_FRAUD = "font_and_encryption_fraud"
    PAGE_HASH_FRAUD = "page_hash_fraud"
    IDENTITY_NAME_FRAUD = "identity_name_fraud"
    RGB_FRAUD = "rgb_fraud"
    GOOD_AUTHOR_FRAUD = "good_author_fraud"
    TAG_HEX_FRAUD = "tag_hex_fraud"
    FLAG_000RG_50_FRAUD = "flag_000rg_50_fraud"
    TAG_HEX_ON_PAGE_CNT_FRAUD = "tag_hex_on_page_cnt_fraud"
    TD_CNT_FRAUD = "TD_cnt_fraud"
    TJ_CNT_FRAUD = "TJ_cnt_fraud"
    TOUCHUP_TEXTEDIT_FRAUD = "touchup_textedit_fraud"
    CNT_OF_PAGEFONTS_NOT_EQUAL_FRAUD = "cnt_of_pagefonts_not_equal_fraud"
    GOOD_FONT_TYPE_SIZE_FRAUD = "good_font_type_size_fraud"
    PIKEPDF_EXCEPTION = "pikepdf_exception"
    INCONSISTENT_TRANSACTION = "inconsistent_transaction"
    MORE_CASH_DEPOSITS_THAN_SALARY = "more_cash_deposits_than_salary"
    SALARY_REMAINS_UNCHANGED = "salary_remains_unchanged"
    SALARY_1000_MULTIPLE = "salary_1000_multiple"
    MOSTLY_CASH_TRANSACTIONS = "mostly_cash_transactions"
    EQUAL_CREDIT_DEBIT = "equal_credit_debit"
    MORE_THAN_15_DAYS_CREDIT = "more_than_15_days_credit"
    NEGATIVE_BALANCE = "negative_balance"
    TAX_100_MULTIPLE = "tax_100_multiple"
    MIN_RTGS_AMOUNT = "min_rtgs_amount"
    CASH_DEPOSIT_BANK_HOLIDAY_TRANSACTION = "cash_deposit_bank_holiday_transaction"
    CHQ_BANK_HOLIDAY_TRANSACTION = "chq_bank_holiday_transaction"
    OUTWARD_CHEQUE_BOUNCE_BANK_HOLIDAY_TRANSACTION = "outward_cheque_bounce_bank_holiday_transaction"
    INWARD_CHEQUE_BOUNCE_BANK_HOLIDAY_TRANSACTION = "inward_cheque_bounce_bank_holiday_transaction"