CREATE TABLE transactions(
    org_id LowCardinality(String),
    statement_id UUID,
    page_number Int16,
    sequence_number Int32,
    entity_id UUID,
    link_id String CODEC(ZSTD(1)),
    org_name LowCardinality(String),
    bank_name LowCardinality(String),
    account_id UUID,
    account_number LowCardinality(String),
    template_id String CODEC(ZSTD(1)),
    transaction_type LowCardinality(String),
    transaction_note String CODEC(ZSTD(1)),
    chq_num LowCardinality(String),
    amount Float32,
    balance Float32,
    date DateTime,
    optimizations String CODEC(ZSTD(1)),
    transaction_channel LowCardinality(String),
    transaction_channel_regex String CODEC(ZSTD(1)),
    hash LowCardinality(String),
    unclean_merchant LowCardinality(String),
    unclean_merchant_regex String CODEC(ZSTD(1)),
    merchant_category LowCardinality(String),
    description String CODEC(ZSTD(1)),
    is_lender Bool,
    merchant LowCardinality(String),
    description_regex String CODEC(ZSTD(1)),
    category LowCardinality(String),
    perfios_txn_category LowCardinality(String),
    created_at DateTime,
    updated_at DateTime,
    attempt_type Nullable(Enum('pdf' = 1, 'aa', 'online', 'csv', 'xml')),
    from_date Nullable(DateTime),
    to_date Nullable(DateTime),
    txn_from_date Nullable(DateTime),
    txn_to_date Nullable(DateTime),
    statement_status Nullable(Int8),
    is_extracted_by_perfios Nullable(Bool),
    is_extracted_by_nanonets Nullable(Bool),
    matched_transaction_currency String CODEC(ZSTD(1)),
    creditor_name String CODEC(ZSTD(1)),
    creditor_ifsc String CODEC(ZSTD(1)),
    creditor_upi_handle String CODEC(ZSTD(1)),
    creditor_bank String CODEC(ZSTD(1)),
    creditor_account_number String CODEC(ZSTD(1)),
    receiver_name String CODEC(ZSTD(1)),
    receiver_ifsc String CODEC(ZSTD(1)),
    receiver_upi_handle String CODEC(ZSTD(1)),
    receiver_bank String CODEC(ZSTD(1)),
    reciever_account_number String CODEC(ZSTD(1)),
    merchant_name String CODEC(ZSTD(1)),
    merchant_ifsc String CODEC(ZSTD(1)),
    merchant_upi_handle String CODEC(ZSTD(1)),
    merchant_bank String CODEC(ZSTD(1)),
    matched_merchant_category String CODEC(ZSTD(1)),
    cheque_number String CODEC(ZSTD(1)),
    transaction_reference_1 String CODEC(ZSTD(1)),
    transaction_reference_2 String CODEC(ZSTD(1)),
    primary_channel String CODEC(ZSTD(1)),
    secondary_channel String CODEC(ZSTD(1)),
    tertiary_channel String CODEC(ZSTD(1)),
    transaction_timestamp String CODEC(ZSTD(1)),
    transaction_amount String CODEC(ZSTD(1)),
    raw_location String CODEC(ZSTD(1)),
    currency String CODEC(ZSTD(1)),
    categorization_time_stamp String CODEC(ZSTD(1)),
    regex_id String CODEC(ZSTD(1)),
    matched_transaction_category String CODEC(ZSTD(1)),
    salary_confidence_percentage Nullable(Int8),
    salary_calculation_method Nullable(Enum('keyword' = 1, 'employer_name', 'recurring')),
    account_category String CODEC(ZSTD(1)),
    is_od_account String CODEC(ZSTD(1)),
    name String CODEC(ZSTD(1))
)
ENGINE = MergeTree 
PARTITION BY toYYYYMM(created_at)
ORDER BY (org_id, entity_id, account_id, statement_id, page_number, sequence_number);
