CREATE TABLE identity(
    org_id LowCardinality(String),
    org_name LowCardinality(String),
    link_id String CODEC(ZSTD(1)),
    session_flow Nullable(Bool),
    entity_id UUID,
    account_id Nullable(UUID),
    statement_id UUID,
    bank_name LowCardinality(String),
    name String CODEC(ZSTD(1)),
    account_number String CODEC(ZSTD(1)),
    address String CODEC(ZSTD(1)),
    attempt_type Nullable(Enum('pdf' = 1, 'online', 'aa', 'csv', 'xml')),
    is_processing_requested Nullable(Bool),
    statement_status Nullable(Int8),
    statement_created_at Nullable(DateTime64),
    from_date Nullable(DateTime),
    to_date Nullable(DateTime),
    extracted_from_date Nullable(DateTime),
    extracted_to_date Nullable(DateTime),
    session_from_date Nullable(DateTime),
    session_to_date Nullable(DateTime),
    account_category Nullable(Enum('corporate' = 1, 'current', 'individual', 'overdraft', 'CURRENT', 'individal', 'SAVINGS')),
    input_account_category Nullable(Enum('corporate' = 1, 'individual')),
    input_is_od_account Nullable(Bool),
    is_od_account Nullable(Bool),
    credit_limit Nullable(Float64),
    od_limit Nullable(Float64),
    ifsc String CODEC(ZSTD(1)),
    micr String CODEC(ZSTD(1)),
    page_count Nullable(Int16),
    transaction_count Nullable(Int32),
    is_ocr_extracted Nullable(Bool),
    is_multi_account_statement Nullable(Bool),
    child_statement_list Array(String),
    parent_statement_id Nullable(UUID),
    fraud_list Array(Int16),
    preshared_names Array(String),
    name_match_analysis String CODEC(ZSTD(1)),
    od_limit_input_by_customer Nullable(Float64),
    is_extracted_by_perfios Nullable(Bool),
    perfios_account_category LowCardinality(String),
    raw_account_category String CODEC(ZSTD(1)),
    updated_od_paramters_by String CODEC(ZSTD(1)),
    country_code LowCardinality(String),
    currency_code LowCardinality(String),
    od_metadata String CODEC(ZSTD(1)),
    opening_date Nullable(DateTime),
    opening_bal Nullable(Float64),
    closing_bal Nullable(Float64),
    keywords_in_line Nullable(Bool),
    all_keywords_present Nullable(Bool),
    amount_keyword_present Nullable(Bool),
    balance_keyword_present Nullable(Bool),
    date_keyword_present Nullable(Bool),
    pdf_hash String CODEC(ZSTD(1)),
    logo_hash String CODEC(ZSTD(1)),
    is_extracted Nullable(Bool),
    is_complete Nullable(Bool),
    is_inconsistent Nullable(Bool),
    inconsistent_hash String CODEC(ZSTD(1)),
    account_number_template_uuid String CODEC(ZSTD(1)),
    name_template_uuid String CODEC(ZSTD(1)),
    address_template_uuid String CODEC(ZSTD(1)),
    ifsc_template_uuid String CODEC(ZSTD(1)),
    micr_template_uuid String CODEC(ZSTD(1)),
    currency_template_uuid String CODEC(ZSTD(1)),
    account_category_template_uuid String CODEC(ZSTD(1)),
    credit_limit_template_uuid String CODEC(ZSTD(1)),
    od_limit_template_uuid String CODEC(ZSTD(1)),
    od_account_template_uuid String CODEC(ZSTD(1)),
    date_range_template_uuid String CODEC(ZSTD(1)),
    opening_date_template_uuid String CODEC(ZSTD(1)),
    opening_bal_template_uuid String CODEC(ZSTD(1)),
    closing_bal_template_uuid String CODEC(ZSTD(1)),
    created_at DateTime64,
    updated_at DateTime64
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(created_at)
ORDER BY (entity_id, statement_id);

ALTER TABLE identity MODIFY COLUMN account_category Nullable(Enum('corporate' = 1, 'current', 'individual', 'overdraft', 'CURRENT', 'individal', 'SAVINGS', 'SB', 'Current', 'Saving', 'OTHERS', 'null', 'Savings'))