CREATE TABLE ccidentityQueue(
    org_id LowCardinality(String),
    org_name LowCardinality(String),
    link_id String CODEC(ZSTD(1)),
    entity_id UUID,
    statement_id UUID,
    bank LowCardinality(String),
    credit_card_number String CODEC(ZSTD(1)),
    name String CODEC(ZSTD(1)),
    address String CODEC(ZSTD(1)),
    payment_due_date Nullable(DateTime64),
    total_dues String CODEC(ZSTD(1)),
    min_amt_due String CODEC(ZSTD(1)),
    credit_limit String CODEC(ZSTD(1)),
    avl_credit_limit String CODEC(ZSTD(1)),
    avl_cash_limit String CODEC(ZSTD(1)),
    opening_balance String CODEC(ZSTD(1)),
    payment_or_credits String CODEC(ZSTD(1)),
    purchase_or_debits String CODEC(ZSTD(1)),
    finance_charges String CODEC(ZSTD(1)),
    statement_date Nullable(DateTime64),
    card_type String CODEC(ZSTD(1)),
    closing_balance String CODEC(ZSTD(1)),
    points_expired String CODEC(ZSTD(1)),
    points_claimed String CODEC(ZSTD(1)),
    points_credited String CODEC(ZSTD(1)),
    from_date Nullable(DateTime64),
    to_date Nullable(DateTime64),
    is_calculated_payment_due_date Nullable(Bool),
    created_at DateTime64,
    updated_at DateTime64,
    credit_card_number_template_uuid LowCardinality(String),
    credit_card_number_page_number Int16,
    name_template_uuid LowCardinality(String),
    name_page_number Int16,
    address_template_uuid LowCardinality(String),
    address_page_number Int16,
    payment_due_date_template_uuid LowCardinality(String),
    payment_due_date_page_number Int16,
    total_dues_template_uuid LowCardinality(String),
    total_dues_page_number Int16,
    min_amt_due_template_uuid LowCardinality(String),
    min_amt_due_page_number Int16,
    credit_limit_template_uuid LowCardinality(String),
    credit_limit_page_number Int16,
    avl_credit_limit_template_uuid LowCardinality(String),
    avl_credit_limit_page_number Int16,
    avl_cash_limit_template_uuid LowCardinality(String),
    avl_cash_limit_page_number Int16,
    opening_balance_template_uuid LowCardinality(String),
    opening_balance_page_number Int16,
    payment_or_credits_template_uuid LowCardinality(String),
    payment_or_credits_page_number Int16,
    purchase_or_debits_template_uuid LowCardinality(String),
    purchase_or_debits_page_number Int16,
    finance_charges_template_uuid LowCardinality(String),
    finance_charges_page_number Int16,
    statement_date_template_uuid LowCardinality(String),
    statement_date_page_number Int16,
    card_type_template_uuid LowCardinality(String),
    card_type_page_number Int16,
    rewards_opening_balance_template_uuid LowCardinality(String),
    rewards_opening_balance_page_number Int16,
    rewards_closing_balance_template_uuid LowCardinality(String),
    rewards_closing_balance_page_number Int16,
    rewards_points_expired_template_uuid LowCardinality(String),
    rewards_points_expired_page_number Int16,
    rewards_points_claimed_template_uuid LowCardinality(String),
    rewards_points_claimed_page_number Int16,
    rewards_points_credited_template_uuid LowCardinality(String),
    rewards_points_credited_page_number Int16
) ENGINE = S3Queue(
    'https://{AWS_BUCKET_URL}/cc_identity/*/*',
    -- edit the aws bucket url here, each * represents YYYYMMDDHH
    JSONEachRow
) SETTINGS mode = 'unordered',
s3queue_enable_logging_to_s3queue_log = 1,
after_processing = 'delete';

CREATE TABLE cc_identity(
    org_id LowCardinality(String),
    org_name LowCardinality(String),
    link_id String CODEC(ZSTD(1)),
    entity_id UUID,
    statement_id UUID,
    bank LowCardinality(String),
    credit_card_number String CODEC(ZSTD(1)),
    name String CODEC(ZSTD(1)),
    address String CODEC(ZSTD(1)),
    payment_due_date Nullable(DateTime64),
    total_dues String CODEC(ZSTD(1)),
    min_amt_due String CODEC(ZSTD(1)),
    credit_limit String CODEC(ZSTD(1)),
    avl_credit_limit String CODEC(ZSTD(1)),
    avl_cash_limit String CODEC(ZSTD(1)),
    opening_balance String CODEC(ZSTD(1)),
    payment_or_credits String CODEC(ZSTD(1)),
    purchase_or_debits String CODEC(ZSTD(1)),
    finance_charges String CODEC(ZSTD(1)),
    statement_date Nullable(DateTime64),
    card_type String CODEC(ZSTD(1)),
    closing_balance String CODEC(ZSTD(1)),
    points_expired String CODEC(ZSTD(1)),
    points_claimed String CODEC(ZSTD(1)),
    points_credited String CODEC(ZSTD(1)),
    from_date Nullable(DateTime64),
    to_date Nullable(DateTime64),
    is_calculated_payment_due_date Nullable(Bool),
    created_at DateTime64,
    updated_at DateTime64,
    credit_card_number_template_uuid LowCardinality(String),
    credit_card_number_page_number Int16,
    name_template_uuid LowCardinality(String),
    name_page_number Int16,
    address_template_uuid LowCardinality(String),
    address_page_number Int16,
    payment_due_date_template_uuid LowCardinality(String),
    payment_due_date_page_number Int16,
    total_dues_template_uuid LowCardinality(String),
    total_dues_page_number Int16,
    min_amt_due_template_uuid LowCardinality(String),
    min_amt_due_page_number Int16,
    credit_limit_template_uuid LowCardinality(String),
    credit_limit_page_number Int16,
    avl_credit_limit_template_uuid LowCardinality(String),
    avl_credit_limit_page_number Int16,
    avl_cash_limit_template_uuid LowCardinality(String),
    avl_cash_limit_page_number Int16,
    opening_balance_template_uuid LowCardinality(String),
    opening_balance_page_number Int16,
    payment_or_credits_template_uuid LowCardinality(String),
    payment_or_credits_page_number Int16,
    purchase_or_debits_template_uuid LowCardinality(String),
    purchase_or_debits_page_number Int16,
    finance_charges_template_uuid LowCardinality(String),
    finance_charges_page_number Int16,
    statement_date_template_uuid LowCardinality(String),
    statement_date_page_number Int16,
    card_type_template_uuid LowCardinality(String),
    card_type_page_number Int16,
    rewards_opening_balance_template_uuid LowCardinality(String),
    rewards_opening_balance_page_number Int16,
    rewards_closing_balance_template_uuid LowCardinality(String),
    rewards_closing_balance_page_number Int16,
    rewards_points_expired_template_uuid LowCardinality(String),
    rewards_points_expired_page_number Int16,
    rewards_points_claimed_template_uuid LowCardinality(String),
    rewards_points_claimed_page_number Int16,
    rewards_points_credited_template_uuid LowCardinality(String),
    rewards_points_credited_page_number Int16
)

ENGINE = MergeTree PARTITION BY toYYYYMM(created_at)
ORDER BY (org_id, bank);

CREATE MATERIALIZED VIEW ccidentityConsumer TO cc_identity AS
SELECT *
FROM ccidentityQueue;