JSON_OUTPUT_FORMAT_FUNCTION_MAP = {
    "CustomerInfo": "get_customer_info",
    "Statementdetails": "get_statement_details",
    "AccountAnalysis": "get_account_analysis",
    "CombinedMonthlyDetails": "get_combined_monthly_details",
    "AdditionalABBSummaryDetails": "get_additional_ABB_summary_details",
    "AdditionalMonthlyFinOneDetails": "get_additional_monthly_finone_details",
    "AdditionalOverallDetails": "get_additional_overall_details",
    "AdditionalPartialMonthDetails": "get_additional_partial_month_details",
    "AdditionalMonthlyDetails": "get_additional_monthly_details",
    "Xns": "get_transactions"
}

LOCAL_FUNCTION_ARGUMENT_MAP = {
    "get_customer_info": ["entity_id", "account_list", "bank_mapping"],
    "get_statement_details": ["account_list", "entity_id", "entity_fraud_dict", "bank_mapping", "to_reject_account"],
    "get_account_analysis": ["account_list", "bank_mapping", "eod_balances_dict", "entity_id",
                             "account_transactions_dict", "monthly_analysis", "month_dict", "entity_fraud_dict",
                             "predictors", "to_reject_account"],
    "get_combined_monthly_details": ["monthly_details_dict"],
    "get_additional_ABB_summary_details": ["account_list", "predictors"],
    "get_additional_monthly_finone_details": ["account_list", "month_dict", "monthly_analysis"],
    "get_additional_overall_details": ["account_list", "predictors"],
    "get_additional_partial_month_details": ["account_list"],
    "get_additional_monthly_details": ["account_list", "monthly_analysis", "predictors", "month_dict"],
    "get_transactions": ["account_list", "account_transactions_dict"]
}

SUMMARY_INFO_TOTAL_FIELD_MAP = {
    "avgUtilization": ["predictors", "nan"],
    "bal10": ["predictors", "total_of_eod_bal_on_10"],
    "bal15": ["predictors", "total_of_eod_bal_on_15"],
    "bal17": ["predictors", "total_of_eod_bal_on_17"],
    "bal2": ["predictors", "total_of_eod_bal_on_02"],
    "bal20": ["predictors", "total_of_eod_bal_on_20"],
    "bal25": ["predictors", "total_of_eod_bal_on_25"],
    "bal30": ["predictors", "total_of_eod_bal_on_30"],
    "bal4": ["predictors", "total_of_eod_bal_on_04"],
    "bal5": ["predictors", "total_of_eod_bal_on_05"],
    "balAvg": ["predictors", "total_of_avg_monthly_bal"],
    "balLast": ["predictors", "sum_of_closing_balance"],
    "balMax": ["predictors", "sum_of_max_eod_balance"],
    "balMin": ["predictors", "sum_of_min_eod_balance"],
    "balTopNAvg": ["predictors", "sum_of_avg_bal_top_15_days"],
    "cashDeposits": ["predictors", "total_cnt_cash_deposit_credit"],
    "cashWithdrawals": ["predictors", "cash_withdrawals"],
    "chqDeposits": ["predictors", "total_number_of_chq_deposits"],
    "chqIssues": ["predictors", "chq_issues"],
    "credits": ["predictors", "nan"],
    "creditsSC": ["predictors", "nan"],
    "creditsSelf": ["predictors", "total_number_of_self_credits"],
    "debits": ["predictors", "nan"],
    "debitsSC": ["predictors", "nan"],
    "debitsSelf": ["predictors", "total_number_of_self_debits"],
    "dpLimit": ["predictors", "nan"],
    "emiOrLoans": ["predictors", "total_number_of_emi_debits"],
    "intPayDelay": ["predictors", "nan"],
    "inwBounceNonTechnical": ["predictors", "total_cnt_of_emi_bounce_non_tech_reason_credit"],
    "inwBounceTechnical": ["predictors", "total_cnt_of_emi_bounce_tech_reason_credit"],
    "inwBounces": ["predictors", "total_cnt_of_emi_bounce_credit"],
    "inwChqBounceNonTechnical": ["predictors", "total_cnt_inward_cheque_bounce_non_tech_reason_credit"],
    "inwEMIBounces": ["predictors", "nan"],
    "loanDisbursals": ["predictors", "total_cnt_of_loan_credits"],
    "outwBounces": ["predictors", "cnt_outward_cheque_bounce_debit"],
    "overdrawnAmount": ["predictors", "nan"],
    "overdrawnDays": ["predictors", "nan"],
    "overdrawnDaysPeak": ["predictors", "nan"],
    "overdrawnInstances": ["predictors", "nan"],
    "salaries": ["predictors", "total_number_of_salary_credits"],
    "snLimit": ["predictors", "nan"],
    "totalBankCharge": ["predictors", "debitless_charges"],
    "totalCashDeposit": ["predictors", "total_amt_cash_deposit"],
    "totalCashWithdrawal": ["predictors", "total_cash_withdrawal"],
    "totalChqDeposit": ["predictors", "total_chq_deposit"],
    "totalChqIssue": ["predictors", "total_chq_issue"],
    "totalCredit": ["predictors", "nan"],
    "totalCreditCardPayment": ["predictors", "total_creditcard_payment"],
    "totalCreditSC": ["predictors", "nan"],
    "totalCreditSelf": ["predictors", "amt_self_transfer_credit"],
    "totalDebit": ["predictors", "nan"],
    "totalDebitSC": ["predictors", "nan"],
    "totalDebitSelf": ["predictors", "total_amt_self_transfer_debit"],
    "totalEmiIssue": ["predictors", "nan"],
    "totalEmiOrLoan": ["predictors", "total_emi_ecs_loan"],
    "totalInterestCharged": ["predictors", "total_amt_of_interest_charged"],
    "totalInterestIncome": ["predictors", "amt_interest_credit"],
    "totalInvExpense": ["predictors", "total_amt_of_investment_expense"],
    "totalInvIncome": ["predictors", "total_amt_of_investment_income"],
    "totalLoanDisbursal": ["predictors", "amt_loan_credit"],
    "totalOtherExpense": ["predictors", "total_amt_of_other_expenses"],
    "totalOtherIncome": ["predictors", "total_amt_of_other_income_credits"],
    "totalPaidSalary": ["predictors", "total_salary_paid"],
    "totalPension": ["predictors", "total_amt_of_pension_credited"],
    "totalSalary": ["predictors", "total_salary_credits"],
    "totalUtilityExpense": ["predictors", "total_utility_payment_amt"]
}

SUMMARY_INFO_AVERAGE_FIELD_MAP = {
    "avgUtilization": ["predictors", "nan"],
    "bal10": ["predictors", "avg_of_eod_bal_on_10"],
    "bal15": ["predictors", "avg_of_eod_bal_on_15"],
    "bal17": ["predictors", "avg_of_eod_bal_on_17"],
    "bal2": ["predictors", "avg_of_eod_bal_on_02"],
    "bal20": ["predictors", "avg_of_eod_bal_on_20"],
    "bal25": ["predictors", "avg_of_eod_bal_on_25"],
    "bal30": ["predictors", "avg_of_eod_bal_on_30"],
    "bal4": ["predictors", "avg_of_eod_bal_on_04"],
    "bal5": ["predictors", "avg_of_eod_bal_on_05"],
    "balAvg": ["predictors", "avg_of_avg_monthly_bal"],
    "balLast": ["predictors", "avg_of_closing_balance"],
    "balMax": ["predictors", "avg_of_max_eod_balance"],
    "balMin": ["predictors", "avg_of_min_eod_balance"],
    "balTopNAvg": ["predictors", "avg_of_avg_bal_top_15_days"],
    "cashDeposits": ["predictors", "avg_cnt_cash_deposit_credit"],
    "cashWithdrawals": ["predictors", "avg_cnt_cash_withdrawl_debit"],
    "chqDeposits": ["predictors", "avg_number_of_chq_deposits"],
    "chqIssues": ["predictors", "avg_number_of_chq_issues"],
    "credits": ["predictors", "nan"],
    "creditsSC": ["predictors", "nan"],
    "creditsSelf": ["predictors", "avg_number_of_self_credits"],
    "debits": ["predictors", "nan"],
    "debitsSC": ["predictors", "nan"],
    "debitsSelf": ["predictors", "avg_number_of_self_debits"],
    "dpLimit": ["predictors", "nan"],
    "emiOrLoans": ["predictors", "avg_number_of_emi_debits"],
    "intPayDelay": ["predictors", "nan"],
    "inwBounceNonTechnical": ["predictors", "avg_cnt_of_emi_bounce_non_tech_reason_credit"],
    "inwBounceTechnical": ["predictors", "avg_cnt_of_emi_bounce_tech_reason_credit"],
    "inwBounces": ["predictors", "avg_cnt_of_emi_bounce_credit"],
    "inwChqBounceNonTechnical": ["predictors", "avg_cnt_inward_cheque_bounce_non_tech_reason_credit"],
    "inwEMIBounces": ["predictors", "nan"],
    "loanDisbursals": ["predictors", "avg_cnt_of_loan_credits"],
    "outwBounces": ["predictors", "avg_cnt_of_outward_cheque_bounce_debit"],
    "overdrawnAmount": ["predictors", "nan"],
    "overdrawnDays": ["predictors", "nan"],
    "overdrawnDaysPeak": ["predictors", "nan"],
    "overdrawnInstances": ["predictors", "nan"],
    "salaries": ["predictors", "avg_number_of_salary_credits"],
    "snLimit": ["predictors", "nan"],
    "totalBankCharge": ["predictors", "avg_monthly_amt_of_bank_charge_debit"],
    "totalCashDeposit": ["predictors", "avg_monthly_amt_cash_deposit"],
    "totalCashWithdrawal": ["predictors", "avg_monthly_amt_cash_withdrawal"],
    "totalChqDeposit": ["predictors", "avg_monthly_amt_cheque_deposited"],
    "totalChqIssue": ["predictors", "avg_monthly_amt_cheque_issue"],
    "totalCredit": ["predictors", "nan"],
    "totalCreditCardPayment": ["predictors", "avg_monthly_amt_credit_card_payment"],
    "totalCreditSC": ["predictors", "nan"],
    "totalCreditSelf": ["predictors", "avg_monthly_amt_self_credit"],
    "totalDebit": ["predictors", "nan"],
    "totalDebitSC": ["predictors", "nan"],
    "totalDebitSelf": ["predictors", "avg_monthly_amt_self_transfer_debit"],
    "totalEmiIssue": ["predictors", "nan"],
    "totalEmiOrLoan": ["predictors", "avg_monthly_amt_of_emi_debit"],
    "totalInterestCharged": ["predictors", "avg_monthly_amt_of_interest_charged"],
    "totalInterestIncome": ["predictors", "avg_monthly_amt_of_interest_credit"],
    "totalInvExpense": ["predictors", "avg_monthly_amt_of_investment_expense"],
    "totalInvIncome": ["predictors", "avg_monthly_amt_of_investment_income"],
    "totalLoanDisbursal": ["predictors", "avg_monthly_amt_of_loan_credits"],
    "totalOtherExpense": ["predictors", "avg_monthly_amt_of_other_expenses"],
    "totalOtherIncome": ["predictors", "avg_monthly_amt_of_other_income_credits"],
    "totalPaidSalary": ["predictors", "avg_monthly_amt_of_salary_paid"],
    "totalPension": ["predictors", "avg_monthly_amt_of_pension_credited"],
    "totalSalary": ["predictors", "avg_monthly_amt_of_salary_credits"],
    "totalUtilityExpense": ["predictors", "avg_monthly_utility_payment_amt"]
}

ACCOUNT_ANALYSIS_MONTHLY_DETAIL = {
    "avgUtilization": ["monthly_analysis", "avg_amt_overdraft_utilization"],
    "bal10": ["monthly_analysis", "eod_bal_on_10"],
    "bal15": ["monthly_analysis", "eod_bal_on_15"],
    "bal17": ["monthly_analysis", "eod_bal_on_17"],
    "bal2": ["monthly_analysis", "eod_bal_on_02"],
    "bal20": ["monthly_analysis", "eod_bal_on_20"],
    "bal25": ["monthly_analysis", "eod_bal_on_25"],
    "bal30": ["monthly_analysis", "eod_bal_on_30"],
    "bal4": ["monthly_analysis", "eod_bal_on_04"],
    "bal5": ["monthly_analysis", "eod_bal_on_05"],
    "balAvg": ["monthly_analysis", "avg_bal"],
    "balLast": ["monthly_analysis", "closing_balance"],
    "balMax": ["monthly_analysis", "max_eod_balance"],
    "balMin": ["monthly_analysis", "min_eod_balance"],
    "balTopNAvg": ["monthly_analysis", "avg_bal_top_15_days"],
    "cashDeposits": ["monthly_analysis", "cnt_cash_deposit_credit"],
    "cashWithdrawals": ["monthly_analysis", "cnt_cash_withdrawl_debit"],
    "chqDeposits": ["monthly_analysis", "cnt_chq_credit"],
    "chqIssues": ["monthly_analysis", "cnt_chq_debit"],
    "credits": ["monthly_analysis", "cnt_credit"],
    "creditsSC": ["monthly_analysis", "nan"],
    "creditsSelf": ["monthly_analysis", "cnt_self_transfer_credit"],
    "debits": ["monthly_analysis", "cnt_debit"],
    "debitsSC": ["monthly_analysis", "nan"],
    "debitsSelf": ["monthly_analysis", "cnt_self_transfer_debit"],
    "dpLimit": ["monthly_analysis", "nan"],
    "emiOrLoans": ["monthly_analysis", "cnt_emi_debit"],
    "highestSalaryDate": ["monthly_analysis", "highest_salary_date"],
    "intPayDelay": ["monthly_analysis", "nan"],
    "inwBounceNonTechnical": ["monthly_analysis", "cnt_emi_bounce_non_tech_reason_credit"],
    "inwBounceTechnical": ["monthly_analysis", "cnt_emi_bounce_tech_reason_credit"],
    "inwBounces": ["monthly_analysis", "cnt_emi_bounce_credit"],
    "inwChqBounceNonTechnical": ["monthly_analysis", "cnt_inward_cheque_bounce_non_tech_reason_credit"],
    "inwEMIBounces": ["monthly_analysis", "nan"],
    "loanDisbursals": ["monthly_analysis", "cnt_loan_credits"],
    # "monthName": ["predictors", "nan"],
    "outwBounces": ["monthly_analysis", "cnt_outward_cheque_bounce_debit"],
    "overdrawnAmount": ["monthly_analysis", "nan"],
    "overdrawnDays": ["monthly_analysis", "nan"],
    "overdrawnDaysPeak": ["monthly_analysis", "nan"],
    "overdrawnInstances": ["monthly_analysis", "nan"],
    "salaries": ["monthly_analysis", "number_of_salary_transactions"],
    "snLimit": ["monthly_analysis", "nan"],
    "startDate": ["monthly_analysis", "start_date"],
    "totalBankCharge": ["monthly_analysis", "amt_bank_charge_debit"],
    "totalCashDeposit": ["monthly_analysis", "amt_cash_deposit_credit"],
    "totalCashWithdrawal": ["monthly_analysis", "amt_cash_withdrawl_debit"],
    "totalChqDeposit": ["monthly_analysis", "amt_chq_credit"],
    "totalChqIssue": ["monthly_analysis", "amt_chq_debit"],
    "totalCredit": ["monthly_analysis", "amt_credit"],
    "totalCreditCardPayment": ["monthly_analysis", "amt_credit_card_bill_debit"],
    "totalCreditSC": ["monthly_analysis", "nan"],
    "totalCreditSelf": ["monthly_analysis", "amt_self_transfer_credit"],
    "totalDebit": ["monthly_analysis", "amt_debit"],
    "totalDebitSC": ["monthly_analysis", "nan"],
    "totalDebitSelf": ["monthly_analysis", "amt_self_transfer_debit"],
    "totalEmiIssue": ["monthly_analysis", "nan"],
    "totalEmiOrLoan": ["monthly_analysis", "amt_emi_debit"],
    "totalInterestCharged": ["monthly_analysis", "amt_interest_charged"],
    "totalInterestIncome": ["monthly_analysis", "amt_bank_interest_credit"],
    "totalInvExpense": ["monthly_analysis", "amt_investment"],
    "totalInvIncome": ["monthly_analysis", "amt_investment_income_credits"],
    "totalLoanDisbursal": ["monthly_analysis", "amt_loan_credits"],
    "totalOtherExpense": ["monthly_analysis", "amt_other_expenses"],
    "totalOtherIncome": ["monthly_analysis", "amt_other_credits"],
    "totalPaidSalary": ["monthly_analysis", "amt_salary_paid"],
    "totalPension": ["monthly_analysis", "amt_pension_credit"],
    "totalSalary": ["monthly_analysis", "total_amount_of_salary"],
    "totalUtilityExpense": ["monthly_analysis", "amt_bill_payment_debit"]
}

ADDITIONAL_ABB_SUMMARY_DETAILS = {
    "AverageBankBalance": ["predictors", "avg_daily_closing_balance"],
    "InwardRTN": ["predictors", "amt_total_bounce_credit"],
    "OutwardRTN": ["predictors", "amt_outward_cheque_bounce_debit"],
    "totalAvgOfTopBalances": ["predictors", "nan"]
}

ADDITIONAL_OVERALL_DETAILS = {
    "last12MonthsAverageBalance": ["predictors", "avg_daily_closing_balance_12months"],
    "last12MonthsCreditAmount": ["predictors", "credits"],
    "last12MonthsCreditCount": ["predictors", "cnt_total_credit_transactions"],
    "last12MonthsDebitAmount": ["predictors", "debits"],
    "last12MonthsDebitCount": ["predictors", "cnt_total_debit_transactions"],
    "last12MonthsInwChqReturn": ["predictors", "amt_inward_cheque_bounce_credit"],
    "last3MonthsAverageBalance": ["predictors", "avg_daily_closing_balance_3months"],
    "last3MonthsCreditAmount": ["predictors", "net_credit_last3months"],
    "last3MonthsCreditCount": ["predictors", "cnt_credit_transactions_3_months"],
    "last3MonthsDebitAmount": ["predictors", "total_debit_amount_last_3_months"],
    "last3MonthsDebitCount": ["predictors", "cnt_debit_transactions_3_months"],
    "last3MonthsInwChqReturn": ["predictors", "amt_inward_cheque_bounce_credit_3_months"],
    "last6MonthsAverageBalance": ["predictors", "avg_daily_closing_balance_6months"],
    "last6MonthsCreditAmount": ["predictors", "total_credit_amount_last_6_months"],
    "last6MonthsCreditCount": ["predictors", "cnt_credit_transactions_last_6_months"],
    "last6MonthsDebitAmount": ["predictors", "total_debit_amount_last_6_months"],
    "last6MonthsDebitCount": ["predictors", "cnt_debit_transactions_last_6_months"],
    "last6MonthsInwChqReturn": ["predictors", "amt_inward_cheque_bounce_credit_6_months"],
    "last9MonthsAverageBalance": ["predictors", "avg_daily_closing_balance_9months"],
    "last9MonthsCreditAmount": ["predictors", "total_credit_amount_last_9_months"],
    "last9MonthsCreditCount": ["predictors", "cnt_credit_transactions_last_9_months"],
    "last9MonthsDebitAmount": ["predictors", "total_debit_amount_last_9_months"],
    "last9MonthsDebitCount": ["predictors", "cnt_debit_transactions_last_9_months"],
    "last9MonthsInwChqReturn": ["predictors", "amt_inward_cheque_bounce_credit_9_months"],
    "negativeBalancesPresent": ["predictors", "negative_balance"]
}

ADDITIONAL_MONTHLY_DETAILS = {
    "avgDaysAccOverdrawn": ["predictors", "nan"],
    "businessCredits": ["monthly_analysis", "cnt_business_credit"],
    "cashDepositsToTotalCredit": ["monthly_analysis", "amt_perc_cash_deposit_to_total_credit"],
    "cashWithdrawalsToTotalDebit": ["monthly_analysis", "amt_perc_cash_withdrawal_to_total_debits"],
    "credits": ["monthly_analysis", "cnt_credit"],
    "debits": ["monthly_analysis", "cnt_debit"],
    "interestServiceDelay": ["monthly_analysis", "nan"],
    "inwBouncesNonTechToDebits": ["monthly_analysis", "amt_perc_non_technical_inward_bounce_to_total_debits"],
    "inwBouncesTechToDebits": ["monthly_analysis", "amt_perc_technical_inward_bounce_to_total_debits"],
    "maxAmtOverdrawn": ["monthly_analysis", "nan"],
    # "monthName": ["predictors", "nan"],
    "outwBouncesToCredits": ["monthly_analysis", "amt_perc_outward_bounce_to_total_credits"],
    "totalBusinessCredit": ["monthly_analysis", "amt_business_credit"],
    "totalCredit": ["monthly_analysis", "amt_credit"],
    "totalDebit": ["monthly_analysis", "amt_debit"]
}

REQUIRED_DATA_TYPES_TO_FUNCTION_MAP = {
    "PREDICTORS": "get_bank_connect_predictors",
    "MONTHLY_ANALYSIS": "get_bank_connect_monthly_analysis",
    "EOD_BALANCES": "get_bank_connect_eod_balances"

}

FUNCTIONS_TO_ARGUMENT_MAP = {
    "get_bank_connect_predictors": ["entity_id", "adjusted_eod", "account_id", "to_remap_predictors",
                                    "ignore_self_transfer", "caching_enabled"],
    "get_bank_connect_monthly_analysis": ["entity_id", "adjusted_eod", "is_sme", "ignore_self_transfer", "caching_enabled"],
    "get_bank_connect_eod_balances": ["entity_id", "adjusted_eod", "is_sme", "to_reject_account", "caching_enabled", "session_dict"]
}

FUNCTION_TO_RETURN_VALUE_MAP = {
    "PREDICTORS": "predictors_global",
    "MONTHLY_ANALYSIS": "monthly_analysis_global",
    "EOD_BALANCES": "eod_balances_global"
}